// app/components/footer.tsx
import Link from 'next/link';
import { SITE, BUSINESS_SERVICES, PERSONAL_SERVICES } from '@/lib/site.config';
import { Phone, Mail, MapPin } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="bg-slate-900 text-white">
      <div className="container mx-auto px-6 py-16">
        {/* Main Footer Content */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-12 mb-16">
          {/* Company Info */}
          <div>
            <h3 className="text-xl font-bold mb-6">{SITE.name}</h3>
            <p className="text-gray-300 mb-6">{SITE.tagline}</p>
            <div className="space-y-3">
              <div className="flex items-center gap-3">
                <Phone size={18} className="text-teal-400" />
                <a href={SITE.phoneHref} className="hover:text-teal-400 transition">
                  {SITE.phone}
                </a>
              </div>
              <div className="flex items-center gap-3">
                <Mail size={18} className="text-teal-400" />
                <a href={`mailto:${SITE.email}`} className="hover:text-teal-400 transition">
                  {SITE.email}
                </a>
              </div>
              <div className="flex items-start gap-3">
                <MapPin size={18} className="text-teal-400 flex-shrink-0 mt-1" />
                <div className="text-sm">
                  {SITE.address.street}, {SITE.address.locality}, {SITE.address.region} {SITE.address.postalCode}
                </div>
              </div>
            </div>
          </div>

          {/* Business Services */}
          <div>
            <h4 className="font-bold mb-6 text-lg">Business Services</h4>
            <ul className="space-y-3">
              {BUSINESS_SERVICES.slice(0, 5).map((service) => (
                <li key={service.link}>
                  <Link href={service.link} className="text-gray-300 hover:text-teal-400 transition">
                    {service.name}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Personal Services */}
          <div>
            <h4 className="font-bold mb-6 text-lg">Personal Services</h4>
            <ul className="space-y-3">
              {PERSONAL_SERVICES.map((service) => (
                <li key={service.link}>
                  <Link href={service.link} className="text-gray-300 hover:text-teal-400 transition">
                    {service.name}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Quick Links */}
          <div>
            <h4 className="font-bold mb-6 text-lg">Company</h4>
            <ul className="space-y-3">
              <li>
                <Link href="/about" className="text-gray-300 hover:text-teal-400 transition">
                  About Us
                </Link>
              </li>
              <li>
                <Link href="/contact" className="text-gray-300 hover:text-teal-400 transition">
                  Contact
                </Link>
              </li>
              <li>
                <Link href="/faq" className="text-gray-300 hover:text-teal-400 transition">
                  FAQ
                </Link>
              </li>
              <li>
                <Link href="/privacy-policy" className="text-gray-300 hover:text-teal-400 transition">
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="/terms" className="text-gray-300 hover:text-teal-400 transition">
                  Terms of Service
                </Link>
              </li>
            </ul>
          </div>
        </div>

        {/* Credentials Section */}
        <div className="border-t border-slate-700 pt-12 mb-8">
          <h4 className="font-bold mb-6 text-lg">Professional Accreditations & Registrations</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-slate-800 p-4 rounded-lg">
              <p className="font-semibold text-teal-400">Company Registration Number</p>
              <p className="text-gray-300 font-mono text-sm mt-2">{SITE.companyNumber}</p>
            </div>
            <div className="bg-slate-800 p-4 rounded-lg">
              <p className="font-semibold text-teal-400">AAT Organisation Number</p>
              <p className="text-gray-300 font-mono text-sm mt-2">{SITE.aatOrgNumber}</p>
            </div>
            <div className="bg-slate-800 p-4 rounded-lg">
              <p className="font-semibold text-teal-400">AAT Licensed Accountancy Practice</p>
              <p className="text-gray-300 text-sm mt-2">Association of Accounting Technicians</p>
            </div>
            <div className="bg-slate-800 p-4 rounded-lg">
              <p className="font-semibold text-teal-400">AML Supervised</p>
              <p className="text-gray-300 text-sm mt-2">Anti-Money Laundering Compliance</p>
            </div>
          </div>
        </div>

        {/* Bottom Footer */}
        <div className="border-t border-slate-700 pt-8 flex flex-col md:flex-row justify-between items-center">
          <p className="text-gray-400 text-sm">
            © {new Date().getFullYear()} {SITE.name}. All rights reserved.
          </p>
          <div className="flex gap-6 mt-4 md:mt-0">
            {SITE.social.linkedin && (
              <a href={SITE.social.linkedin} target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-teal-400 transition">
                LinkedIn
              </a>
            )}
            {SITE.social.instagram && (
              <a href={SITE.social.instagram} target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-teal-400 transition">
                Instagram
              </a>
            )}
            {SITE.social.facebook && (
              <a href={SITE.social.facebook} target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-teal-400 transition">
                Facebook
              </a>
            )}
          </div>
        </div>
      </div>
    </footer>
  );
}

// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { IconComponent } from '../icon/icon.component';
import {
  SITE,
  BUSINESS_SERVICES,
  PERSONAL_SERVICES,
} from '../../core/site.config';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, RouterModule, IconComponent],
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css'],
})
export class FooterComponent {
  site = SITE;
  businessServices = BUSINESS_SERVICES;
  personalServices = PERSONAL_SERVICES;
  year = new Date().getFullYear();
}

<footer class="footer" role="contentinfo">
  <div class="container footer-container">
    <div class="footer-grid">
      <div class="footer-brand">
        <div class="footer-logo">
          <img src="/images/mna-logo.png" alt="MNA Accounting Ltd logo" />
          <span>{{ site.name }}</span>
        </div>
        <p class="footer-blurb">
          Trusted accounting and advisory support for businesses and individuals across Birmingham, the West Midlands and UK-wide.
        </p>

        <div class="footer-contact-block" aria-label="Contact information">
          <a [href]="site.phoneHref" class="footer-contact-row">
            <app-icon name="phone" class="icon-small"></app-icon>
            <span>{{ site.phone }}</span>
          </a>
          <a [href]="'mailto:' + site.email" class="footer-contact-row">
            <app-icon name="mail" class="icon-small"></app-icon>
            <span>{{ site.email }}</span>
          </a>
          <span class="footer-contact-row">
            <app-icon name="mapPin" class="icon-small"></app-icon>
            <span>
              {{ site.address.street }}, {{ site.address.locality }}, {{ site.address.region }} {{ site.address.postalCode }}
            </span>
          </span>
          <span class="footer-contact-row">
            <app-icon name="clock" class="icon-small"></app-icon>
            <span>{{ site.openingHours }}</span>
          </span>
        </div>

        <div class="footer-social" aria-label="Follow us on social media">
          <a [href]="site.social.linkedin" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn" class="social-icon-link">
            <img src="/images/linkedin-icon.png" alt="LinkedIn" class="social-icon" />
          </a>
          <a [href]="site.social.instagram" target="_blank" rel="noopener noreferrer" aria-label="Instagram" class="social-icon-link">
            <img src="/images/instagram-icon.png" alt="Instagram" class="social-icon" />
          </a>
          <a [href]="site.social.facebook" target="_blank" rel="noopener noreferrer" aria-label="Facebook" class="social-icon-link">
            <img src="/images/facebook-icon.png" alt="Facebook" class="social-icon" />
          </a>
          <a [href]="site.social.whatsapp" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp" class="social-icon-link">
            <img src="/images/whatsapp-social.png" alt="WhatsApp" class="social-icon" />
          </a>
        </div>
      </div>

      <nav class="footer-col" aria-label="Business services">
        <h3>Business Services</h3>
        <ul>
          <li *ngFor="let s of businessServices">
            <a [routerLink]="s.link">{{ s.name }}</a>
          </li>
        </ul>
      </nav>

      <nav class="footer-col" aria-label="Personal services">
        <h3>Personal Services</h3>
        <ul>
          <li *ngFor="let s of personalServices">
            <a [routerLink]="s.link">{{ s.name }}</a>
          </li>
        </ul>
      </nav>

      <nav class="footer-col" aria-label="Company and policies">
        <h3>Company</h3>
        <ul>
          <li><a routerLink="/about">About Us</a></li>
          <li><a routerLink="/business">All Services</a></li>
          <li><a routerLink="/contact">Contact</a></li>
          <li><a routerLink="/faq">FAQ</a></li>
          <li><a routerLink="/privacy-policy">Privacy Policy</a></li>
          <li><a routerLink="/terms">Terms of Service</a></li>
        </ul>
      </nav>
    </div>

    <div class="footer-support">
      <div class="footer-support-cards">
        <div class="footer-support-card">
          <h4>Phone support</h4>
          <p>Speak directly with a qualified accountant for fast guidance.</p>
          <a [href]="site.phoneHref">{{ site.phone }}</a>
        </div>
        <div class="footer-support-card">
          <h4>Email enquiries</h4>
          <p>Send us your questions and we will reply within one working day.</p>
          <a [href]="'mailto:' + site.email">{{ site.email }}</a>
        </div>
      </div>

      <a routerLink="/contact" class="btn btn-primary btn-block footer-support-button">
        Request a free consultation
        <app-icon name="arrowRight"></app-icon>
      </a>
    </div>

    <div class="footer-bottom">
      <div class="footer-credentials">
        <h4 class="credentials-title">Professional Accreditations & Registrations</h4>
        <div class="credentials-badges">
          <div class="credential-badge">
            <app-icon name="building2" class="badge-icon-check"></app-icon>
            <div class="badge-content">
              <span class="badge-label">Company Registration Number</span>
              <span class="badge-value">{{ site.companyNumber }}</span>
            </div>
          </div>
          <div class="credential-badge">
            <app-icon name="check" class="badge-icon-check"></app-icon>
            <div class="badge-content">
              <span class="badge-label">AAT Licensed Accountancy Practice</span>
              <span class="badge-note">Association of Accounting Technicians</span>
            </div>
          </div>
          <div class="credential-badge">
            <app-icon name="id" class="badge-icon-check"></app-icon>
            <div class="badge-content">
              <span class="badge-label">AAT Organisation Number</span>
              <span class="badge-value">{{ site.aatOrgNumber }}</span>
            </div>
          </div>
          <div class="credential-badge">
            <app-icon name="shield" class="badge-icon-check"></app-icon>
            <div class="badge-content">
              <span class="badge-label">AML Supervised</span>
              <span class="badge-note">Anti-Money Laundering Compliance</span>
            </div>
          </div>
          <div class="credential-badge">
            <app-icon name="checkCircle" class="badge-icon-check"></app-icon>
            <div class="badge-content">
              <span class="badge-label">Professional Indemnity Insured</span>
              <span class="badge-note">Full Coverage Provided</span>
            </div>
          </div>
          <div class="credential-badge">
            <app-icon name="verified" class="badge-icon-check"></app-icon>
            <div class="badge-content">
              <span class="badge-label">Authorised Director Verification Provider</span>
              <span class="badge-note">Companies House Approved</span>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-copyright-section">
        <p class="footer-copyright">&copy; {{ year }} {{ site.legalName }}. All rights reserved.</p>
        <p class="footer-legal-links">
          <a routerLink="/privacy-policy">Privacy</a>
          <span aria-hidden="true">·</span>
          <a routerLink="/terms">Terms</a>
        </p>
      </div>
    </div>
  </div>
</footer>
