// src/app/pages/faq/faq.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { IconComponent } from '../../components/icon/icon.component';

interface FAQItem {
  id: string;
  question: string;
  answer: string;
  isOpen?: boolean;
}

@Component({
  selector: 'app-faq',
  standalone: true,
  imports: [CommonModule, RouterModule, IconComponent],
  templateUrl: './faq.component.html',
  styleUrl: './faq.component.css',
})
export class FaqComponent {
  faqs: FAQItem[] = [
    {
      id: 'fees',
      question: 'How much do accountants charge?',
      answer: `Our fees are transparent and competitively priced. We offer flexible pricing models including fixed fees for standard services and hourly rates for bespoke work. Most small businesses save 40% compared to traditional high-street accountants. We'll provide a clear quote after understanding your specific needs during a free initial consultation.`,
    },
    {
      id: 'remote',
      question: 'Do you work remotely?',
      answer: `Yes, we work entirely remotely. We serve clients across the UK from our base in Birmingham, including Coventry, Warwickshire, and beyond. Working remotely means lower overheads that we pass on as savings to you. You can communicate with us via phone, email, video call, or in-person meetings at our Birmingham office if preferred.`,
    },
    {
      id: 'companies-house',
      question: 'Can you help with Companies House filings?',
      answer: `Absolutely. As an authorised Companies House Director Verification Provider, we handle all aspects of Companies House compliance including annual accounts filings, director verification, confirmation statements, and statutory compliance. We stay updated with the latest Companies House requirements and ensure your filings are accurate and timely.`,
    },
    {
      id: 'advice-fee',
      question: 'Can I call for business advice and is there a fee?',
      answer: `Yes, you can absolutely call us for business advice. We offer free initial consultations where we discuss your accounting and tax needs with no obligation. For ongoing advice, fees depend on the complexity and scope. Many clients find our advice saves them far more than they pay in fees through tax planning and business optimization.`,
    },
    {
      id: 'lower-fees',
      question: 'I\'m worried about your lower fees.',
      answer: `Our lower fees don't mean lower quality. We achieve efficiency through modern cloud-based accounting systems and streamlined processes. We're AAT licensed, AML supervised, and professionally insured just like traditional high-street practices. Our clients receive the same professional expertise and compliance standards, but without the inflated overhead costs.`,
    },
    {
      id: 'deadlines',
      question: 'Can you keep track of my deadlines?',
      answer: `Yes, we proactively manage all your accounting and tax deadlines. We maintain a comprehensive timeline including tax returns, Companies House filings, VAT submissions, and payroll deadlines. You'll receive reminders well in advance, and we handle submission deadlines to ensure you never miss critical dates. This is a key benefit of our ongoing accounting support.`,
    },
    {
      id: 'charging',
      question: 'How do you charge?',
      answer: `We offer flexible charging options: Fixed fees for standard services (bookkeeping, tax returns, companies house filings), hourly rates for bespoke or consulting work, and retainer packages for ongoing support. We provide transparent quotes upfront with no hidden costs. Payment is typically monthly or quarterly depending on your preference.`,
    },
    {
      id: 'mtd',
      question: 'What is Making Tax Digital (MTD)?',
      answer: `Making Tax Digital (MTD) is HMRC's requirement for businesses to keep digital records and submit tax returns using compatible software. Most businesses with a turnover over £85,000 must comply. We help you navigate MTD compliance by setting up cloud-based accounting systems, integrating approved software like Xero or QuickBooks, and managing your quarterly submissions. Our MTD services ensure you stay compliant without the hassle.`,
    },
  ];

  toggleFaq(faq: FAQItem): void {
    faq.isOpen = !faq.isOpen;
  }
}

<!-- Hero Section -->
<section class="hero">
  <div class="container">
    <div class="hero-content">
      <h1>Frequently Asked Questions</h1>
      <p class="hero-subtitle">
        Find answers to common questions about our accounting services, pricing, and support
      </p>
    </div>
  </div>
</section>

<!-- FAQ Section -->
<section class="faq-section">
  <div class="container">
    <div class="faq-container">
      <div class="faq-header">
        <h2>We're here to help</h2>
        <p>Browse our most commonly asked questions below, or <a routerLink="/contact">contact us</a> if you need more information.</p>
      </div>

      <div class="accordion-wrapper">
        <div class="accordion-item" *ngFor="let faq of faqs" [class.open]="faq.isOpen">
          <button
            class="accordion-trigger"
            (click)="toggleFaq(faq)"
            [attr.aria-expanded]="faq.isOpen"
            [attr.aria-controls]="'faq-' + faq.id"
          >
            <span class="accordion-question">{{ faq.question }}</span>
            <div class="accordion-icon">
              <app-icon name="chevronDown"></app-icon>
            </div>
          </button>

          <div class="accordion-content" [id]="'faq-' + faq.id" role="region">
            <div class="accordion-body">
              <p>{{ faq.answer }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- CTA Section -->
<section class="cta-section">
  <div class="container">
    <div class="cta-content">
      <h2>Still have questions?</h2>
      <p>We're here to help. Get in touch with our team for a free consultation.</p>
      <div class="cta-buttons">
        <a routerLink="/contact" class="cta-primary">
          <app-icon name="mail" class="icon-small"></app-icon>
          Book Free Consultation
        </a>
        <a href="tel:07551551717" class="cta-secondary">
          <app-icon name="phone" class="icon-small"></app-icon>
          Call Us
        </a>
      </div>
    </div>
  </div>
</section>

// app/faq/page.tsx
'use client';

import { useState } from 'react';
import { ChevronDown } from 'lucide-react';

const faqs = [
  {
    question: 'How much do accountants charge?',
    answer: 'Our fees are transparent and competitive. We typically charge between £60-150 per hour depending on the complexity of your work, or we offer fixed-price packages for standard services like bookkeeping and tax returns. Many clients save 30-40% compared to high street accountants.',
  },
  {
    question: 'Do you work remotely?',
    answer: 'Yes! We offer full remote services across the UK. We can manage all your accounting needs online through secure digital systems. You can discuss your account via video call, phone, or email whenever suits you best.',
  },
  {
    question: 'Can you help with Companies House filings?',
    answer: 'Absolutely. As an authorised Companies House Director Verification Provider, we can help with director verifications, company filings, and all statutory obligations. We ensure your company stays compliant with Companies House requirements.',
  },
  {
    question: 'Can I call for business advice and is there a fee?',
    answer: 'Yes, you can call us anytime for advice. We provide free telephone consultations during business hours. For formal advice or complex matters requiring detailed analysis, we\'ll quote beforehand so you know the cost.',
  },
  {
    question: 'I\'m worried about your lower fees.',
    answer: 'Our lower fees don\'t mean lower quality. We use modern cloud-based accounting software and efficient processes to reduce overhead costs. We\'re AAT-licensed with full professional indemnity insurance, and our clients enjoy the same expert service at better value.',
  },
  {
    question: 'Can you keep track of my deadlines?',
    answer: 'Yes. We maintain a deadline tracking system and proactively notify you of upcoming tax deadlines, filing dates, and important compliance dates. You\'ll never miss a deadline with our support.',
  },
  {
    question: 'How do you charge?',
    answer: 'We offer flexible charging options: hourly rates, fixed-price packages for standard services, or monthly retainers for ongoing support. We discuss your needs first and recommend the best option for your situation.',
  },
  {
    question: 'What is Making Tax Digital (MTD)?',
    answer: 'Making Tax Digital (MTD) is HMRC\'s digital tax initiative requiring digital record-keeping and quarterly submissions using approved software. We help set up compliant systems, integrate with software like Xero or QuickBooks, and manage your quarterly submissions so you stay compliant without stress.',
  },
];

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-slate-900 to-slate-800 text-white py-16 md:py-24">
        <div className="container mx-auto px-6 text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">Frequently Asked Questions</h1>
          <p className="text-xl text-gray-300">Find answers to common questions about our services and pricing.</p>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-6 max-w-3xl">
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div
                key={index}
                className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden"
              >
                <button
                  onClick={() => setOpenIndex(openIndex === index ? null : index)}
                  className="w-full px-6 py-4 flex items-center justify-between hover:bg-gray-50 transition"
                >
                  <h3 className="text-left font-semibold text-lg text-gray-900">{faq.question}</h3>
                  <ChevronDown
                    size={24}
                    className={`text-teal-600 flex-shrink-0 transition-transform ${
                      openIndex === index ? 'rotate-180' : ''
                    }`}
                  />
                </button>

                {openIndex === index && (
                  <div className="px-6 py-4 border-t border-gray-200 bg-gray-50">
                    <p className="text-gray-700 leading-relaxed">{faq.answer}</p>
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* CTA */}
          <div className="mt-16 bg-teal-50 border border-teal-200 rounded-lg p-8 text-center">
            <h3 className="text-2xl font-bold text-gray-900 mb-4">Didn't find your answer?</h3>
            <p className="text-gray-700 mb-6">
              Get in touch with our team for a free consultation and we'll answer any questions you have.
            </p>
            <a
              href="/contact"
              className="bg-teal-600 hover:bg-teal-700 text-white px-8 py-3 rounded-lg font-semibold inline-block transition"
            >
              Contact Us
            </a>
          </div>
        </div>
      </section>
    </div>
  );
}
